data_path: ConditionalNeuralField/data/path/to/data
load_data_fn: load_3d_flow

save_path: ConditionalNeuralField/data/save/path/here
coor_path: /add/path/here
lumped_latent: True

normalizer:
  method: '-11'
  dim: 0
batch_size: 4
test_batch_size: 4

multiGPU: 2
readin_data_shape: "t N c"
batch_shape: "t N c"

hidden_size: 384
epochs: 30000

loss_fn: MSELoss
test_criteria: rMAE
save_every: 200

dims: 3

NF:
  name: SIRENAutodecoder_film
  in_coord_features: 3
  out_features: 3
  num_hidden_layers: 15
  hidden_features: 384

lr:
  nf: 1.e-4
  latents: 1.e-5