data_path: /home/xinyang/store/projects/nfdiff/algo/elbow/uvp.npy
load_data_fn: load_elbow_flow

save_path: /home/xinyang/store/projects/nfdiff/algo/elbow/t0
coor_path: /home/xinyang/store/projects/nfdiff/algo/elbow/coor.npy
lumped_latent: True

normalizer:
  method: '-11'
  dim: 0
batch_size: 64
test_batch_size: 256

multiGPU: 1
readin_data_shape: "t N c"
batch_shape: "t N c"

hidden_size: 128
epochs: 100

loss_fn: MSELoss
test_criteria: rMAE
save_every: 5

dims: 2

NF:
  name: SIRENAutodecoder_film
  num_hidden_layers: 10
  out_features: 3
  hidden_features: 128

lr:
  nf: 1.e-4
  latents: 1.e-5
