data_path:
load_data_fn: load_channel_flow

save_path:
# coor_path: /PATH/TO/YOUR/COOR/FOLDER
lumped_latent: False

normalizer:
  method: "-11"
  dim: 0
batch_size: 40
test_batch_size: 40

multiGPU: 2
readin_data_shape: "t h w c"
batch_shape: "t h w c"

hidden_size: 256
epochs: 30000

loss_fn: MSELoss
test_criteria: rMAE
save_every: 200

dims: 2

NF:
  name: SIRENAutodecoder_film
  in_coord_features: 2
  out_features: 3
  num_hidden_layers: 10
  hidden_features: 256

lr:
  nf: 1.e-4
  latents: 1.e-5
